/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StudentRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.enterprise.VisaGovernmentEnterprise;
import business.network.Network;
import business.organization.LegalComplianceOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.VisaSupportRequest;
import business.workqueue.WorkRequest;
import business.workqueue.StudyAbroadApplication;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gerrysu
 */
public class RequestVisaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    
    
    /**
     * Creates new form RequestVisaJPanel
     */
    public RequestVisaJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblCountry = new javax.swing.JLabel();
        lblPassport = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtPassport = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCountry.setText("Issuing Country:");

        lblPassport.setText("Passport NUmber:");

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("Apply for Student Visa");

        lblNote.setText("Note: Financial Proof will be automatically attached from your Financial Aid record.");

        btnSubmit.setText("Submit Application");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblNote))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassport)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCountry)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnSubmit)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassport)
                    .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSubmit)
                .addGap(49, 49, 49)
                .addComponent(lblNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String passport = txtPassport.getText().trim();
    String country = txtCountry.getText().trim();
    
    if(passport.isEmpty() || country.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please fill all fields.");
        return;
    }
    
    // Find accepted application
    business.workqueue.StudyAbroadApplication acceptedApp = null;
    for (business.workqueue.WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof business.workqueue.StudyAbroadApplication) {
            business.workqueue.StudyAbroadApplication app = (business.workqueue.StudyAbroadApplication) wr;
            if ("Offer Accepted".equals(app.getStatus())) {
                acceptedApp = app;
                break;
            }
        }
    }
    
    if (acceptedApp == null) {
        JOptionPane.showMessageDialog(null, "You must accept an offer first.");
        return;
    }
    
    VisaSupportRequest request = new VisaSupportRequest();
    request.setPassportNumber(passport);
    request.setIssuingCountry(country);
    request.setSender(userAccount);
    request.setStatus("Pending Legal Check");
    request.setMessage("Visa App: " + passport);
    request.setStudyAbroadApplication(acceptedApp);
    
    if (acceptedApp.isAidApproved()) {
        request.setFinancialProofVerified(true);
    }
    
    Organization legalOrg = null;
    for (Network n : system.getNetworkList()){
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
            if (e instanceof VisaGovernmentEnterprise){
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    if (o instanceof LegalComplianceOrganization){
                        legalOrg = o;
                        break;
                    }
                }
            }
        }
    }
    
    if(legalOrg != null){
        legalOrg.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Visa Application Submitted.");
        goBack();
    } else {
        JOptionPane.showMessageDialog(null, "Error: Legal Office not found.");
    }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void goBack(){
        userProcessContainer.remove(this);
        // Refresh previous panel logic if needed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtPassport;
    // End of variables declaration//GEN-END:variables
}
