/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StudentRole;

import business.EcoSystem;
import business.useraccount.UserAccount;
import business.workqueue.StudyAbroadApplication;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gerrysu
 */
public class ViewApplicationStatusJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    
    /**
     * Creates new form ViewApplicationStatusJPanel
     */
    public ViewApplicationStatusJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        
        populateTable();
    }
    
    private void populateTable(){
        btnRequestVisa.setEnabled(false); 
        btnAccept.setEnabled(false); 
        
        DefaultTableModel model = (DefaultTableModel) tblStatus.getModel();
        model.setRowCount(0);
        
        boolean hasAcceptedOffer = false;
        
        // 1. 遍历并填充表格，同时检查是否有已接受的 Offer
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof StudyAbroadApplication){
                StudyAbroadApplication app = (StudyAbroadApplication) request;
                String status = request.getStatus();
                if("Offer Accepted".equals(status) || "Visa Issued".equals(status) || "Visa Applied".equals(status)){
                    hasAcceptedOffer = true;
                }
                
                Object[] row = new Object[4];
                row[0] = app;
                row[1] = app.getSelectedUniversity();
                row[2] = status;
                row[3] = app.getResult();
                model.addRow(row);
            }
            else if(request instanceof business.workqueue.InternshipPlacementRequest){
                business.workqueue.InternshipPlacementRequest internReq = (business.workqueue.InternshipPlacementRequest) request;
                
                if("Offer Accepted".equals(internReq.getStatus()) || "Internship Completed".equals(internReq.getStatus())){
                    hasAcceptedOffer = true;
                }

                Object[] row = new Object[4];
                row[0] = internReq; 
                row[1] = internReq.getCompanyPlaced() != null ? internReq.getCompanyPlaced() : "Corporate Internship"; 
                row[2] = internReq.getStatus();
                row[3] = internReq.getResult(); 
                
                model.addRow(row);
            }
        }
        
        // 2. 设置按钮状态
        if(hasAcceptedOffer){
            // 如果已经接受了任何 Offer，就不能再接受其他的
            btnAccept.setEnabled(false); 
            // 只有这时才允许申请签证 (具体还要看选中的行)
            btnRequestVisa.setEnabled(true); 
        } else {
            btnRequestVisa.setEnabled(false); // 没接受 Offer 不能申请签证

            boolean canAccept = false;
            // 再次遍历，检查是否有待接受的 Offer
            for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
                // 检查留学 Offer
                if (request instanceof StudyAbroadApplication) {
                    StudyAbroadApplication app = (StudyAbroadApplication) request;
                    if ("Admitted".equals(app.getStatus()) && app.isAidSaved()) {
                        canAccept = true;
                        break;
                    }
                }
                // 【新增】检查实习 Offer (修复点：加上这块逻辑)
                else if (request instanceof business.workqueue.InternshipPlacementRequest) {
                    if ("Internship Offered".equals(request.getStatus())) {
                        canAccept = true;
                        break;
                    }
                }
            }
            btnAccept.setEnabled(canAccept);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatus = new javax.swing.JTable();
        btnRequestVisa = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setText("Application Status");

        tblStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "University", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStatus);

        btnRequestVisa.setText("Request Visa Support");
        btnRequestVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestVisaActionPerformed(evt);
            }
        });

        btnAccept.setText("Accept Offer");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(lblTitle))
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAccept)
                        .addGap(108, 108, 108)
                        .addComponent(btnRequestVisa)
                        .addGap(242, 242, 242))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestVisa)
                    .addComponent(btnAccept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestVisaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStatus.getSelectedRow();
        if(selectedRow < 0){
             JOptionPane.showMessageDialog(null, "Please select your accepted application.");
             return;
        }
        
        // 1. 获取通用对象，避免崩溃
        WorkRequest request = (WorkRequest)tblStatus.getValueAt(selectedRow, 0);
        
        // 2. 检查是否为留学申请 (通常只有留学需要走这个复杂的 Visa 流程)
        if (request instanceof StudyAbroadApplication) {
            if(!"Offer Accepted".equals(request.getStatus())){
                 JOptionPane.showMessageDialog(null, "You must accept an offer before requesting a visa.");
                 return;
            }
            // 跳转到签证页面
            RequestVisaJPanel visaPanel = new RequestVisaJPanel(userProcessContainer, userAccount, system);
            userProcessContainer.add("RequestVisaJPanel", visaPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
        } else if (request instanceof business.workqueue.InternshipPlacementRequest) {
            // 如果是实习申请，直接弹窗提示不需要签证
            JOptionPane.showMessageDialog(null, "Domestic internships do not require a separate visa application process in this system.");
        }
    }//GEN-LAST:event_btnRequestVisaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        int selectedRow = tblStatus.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select an application.");
            return;
        }

        // 1. 获取通用 WorkRequest 对象 (不要直接强转成 StudyAbroadApplication)
        business.workqueue.WorkRequest request = (business.workqueue.WorkRequest) tblStatus.getValueAt(selectedRow, 0);

        // 2. 判断请求类型并处理
        if (request instanceof business.workqueue.StudyAbroadApplication) {
            // === 原有的留学申请逻辑 ===
            if ("Admitted".equals(request.getStatus())) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Accept University Offer?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    request.setStatus("Offer Accepted");
                    request.setResult("Offer Accepted by Student");
                    JOptionPane.showMessageDialog(null, "University Offer Accepted! You may now request a visa.");
                    populateTable();
                }
            } 
            else {
                JOptionPane.showMessageDialog(null, "You can only accept 'Admitted' applications.");
            }
            
        } else if (request instanceof business.workqueue.InternshipPlacementRequest) {
            business.workqueue.InternshipPlacementRequest internReq = (business.workqueue.InternshipPlacementRequest) request;
            
            if ("Internship Offered".equals(internReq.getStatus())) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Accept Internship Offer?", "Confirm", JOptionPane.YES_NO_OPTION);
                
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // A. 更新状态
                    internReq.setStatus("Offer Accepted");
                    internReq.setResult("Offer Accepted by Student");
                    
                    // B. 【关键步骤】将请求转发给现场主管 (Operations Organization)
                    boolean forwarded = false;
                    
                    // 遍历整个网络，找到 Corporate Enterprise -> Operations Organization
                    for (business.network.Network network : system.getNetworkList()) {
                        for (business.enterprise.Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                            // 找到企业
                            if (ent instanceof business.enterprise.CorporateEnterprise) {
                                for (business.organization.Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                                    // 找到主管所在的部门 (根据 ConfigureASystem，主管在 OperationsOrganization)
                                    if (org instanceof business.organization.OperationsOrganization) {
                                        org.getWorkQueue().getWorkRequestList().add(internReq);
                                        forwarded = true;
                                        System.out.println("Request forwarded to Operations/Supervisor queue.");
                                    }
                                }
                            }
                        }
                    }
                    
                    if (forwarded) {
                        JOptionPane.showMessageDialog(null, "Internship Accepted! Your Site Supervisor has been notified.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Internship Accepted, but could not notify Supervisor (Org not found).");
                    }
                    
                    populateTable();
                }
            } else {
                JOptionPane.showMessageDialog(null, "You can only accept requests with 'Internship Offered' status.");
            }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestVisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblStatus;
    // End of variables declaration//GEN-END:variables
}
