/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FinancialAuditorRole;

import business.EcoSystem;
import business.workqueue.FinancialClearanceRequest;
import javax.swing.JPanel;
/**
 *
 * @author gerrysu
 */
public class ProcessFinancialClearanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessFinancialClearanceJPanel
     */
    private JPanel userProcessContainer;
    private FinancialClearanceRequest request;
    private EcoSystem system;
    
    public ProcessFinancialClearanceJPanel(JPanel userProcessContainer,
                                            FinancialClearanceRequest request, 
                                            EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = system;
        
        populateData();
    }

    private void populateData() {
        // Get the linked StudyAbroadApplication from FinancialClearanceRequest
        business.workqueue.StudyAbroadApplication app = request.getStudentApplication();
        
        if (app != null) {
            // You need to add these text fields in Design mode first
            // txtStudent.setText(app.getSender().getEmployee().getName());
            // txtMajor.setText(app.getMajor());
            // txtTargetUni.setText(app.getSelectedUniversity());
        }
        
        // txtGrantRequested.setText(String.valueOf(request.getGrantAmountRequested()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
