/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FinancialAuditorRole;

import business.EcoSystem;
import business.workqueue.FinancialClearanceRequest;
import business.workqueue.StudyAbroadApplication;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author gerrysu
 */
public class ProcessFinancialClearanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessFinancialClearanceJPanel
     */
    private JPanel userProcessContainer;
    private FinancialClearanceRequest request;
    private EcoSystem system;
    
    public ProcessFinancialClearanceJPanel(JPanel userProcessContainer,
                                            FinancialClearanceRequest request, 
                                            EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = system;
        
        populateData();
    }

    private void populateData() {
    StudyAbroadApplication app = request.getStudentApplication();
    
    if (app == null) {
        JOptionPane.showMessageDialog(null, 
            "Error: Cannot find student application.");
        return;
    }
    
    txtStudent.setText(app.getSender().getEmployee().getName());
    txtMajor.setText(app.getMajor());  
    txtGPA.setText(String.valueOf(app.getCurrentGPA()));  
    txtTargetUni.setText(app.getSelectedUniversity());  
    
    double requestedAmount = request.getGrantAmountRequested();
    if (requestedAmount > 0) {
        txtGrantRequested.setText(String.valueOf(requestedAmount));
    } else {
        txtGrantRequested.setText("N/A");
    }
    
    txtStudent.setEnabled(false);
    txtMajor.setEnabled(false);
    txtGPA.setEnabled(false);
    txtTargetUni.setEnabled(false);
    txtGrantRequested.setEnabled(false);
    
    if (!app.isAidSaved()) {

        btnSaveAid.setEnabled(true);
        btnApprove.setEnabled(false);
        txtApprovedAmount.setEnabled(true);
        
    } else if (app.isAidSaved() && !app.isAidApproved()) {
        btnSaveAid.setEnabled(false);
        txtApprovedAmount.setText(String.valueOf(app.getGrantAmount()));
        txtApprovedAmount.setEnabled(false);
        
        if ("Offer Accepted".equals(app.getStatus())) {
            btnApprove.setEnabled(true);
        } else {
            btnApprove.setEnabled(false);
        }
        
    } else if (app.isAidApproved()) {
        btnSaveAid.setEnabled(false);
        btnApprove.setEnabled(false);
        txtApprovedAmount.setText(String.valueOf(app.getGrantAmount()));
        txtApprovedAmount.setEnabled(false);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        lblMajor = new javax.swing.JLabel();
        txtMajor = new javax.swing.JTextField();
        lblTargetUni = new javax.swing.JLabel();
        txtTargetUni = new javax.swing.JTextField();
        txtGrantRequested = new javax.swing.JTextField();
        lblGrantRequested = new javax.swing.JLabel();
        lblApprovedAmount = new javax.swing.JLabel();
        txtApprovedAmount = new javax.swing.JTextField();
        lblComments = new javax.swing.JLabel();
        txtComments = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSaveAid = new javax.swing.JButton();
        lblGPA = new javax.swing.JLabel();
        txtGPA = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitle.setText("Process Financial Clearance Request");

        lblStudent.setText("Student");

        lblMajor.setText("Major");

        lblTargetUni.setText("Target University:");

        lblGrantRequested.setText("Grant Requested:");

        lblApprovedAmount.setText("Approved Amount:");

        lblComments.setText("Comments:");

        btnApprove.setText(" Approve Scholarship");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSaveAid.setText("Save Aid Amount");
        btnSaveAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAidActionPerformed(evt);
            }
        });

        lblGPA.setText("GPA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMajor)
                            .addComponent(lblTargetUni)
                            .addComponent(lblStudent))
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTargetUni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtMajor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudent)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGrantRequested)
                            .addComponent(lblComments)
                            .addComponent(lblApprovedAmount)
                            .addComponent(lblGPA))
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtComments, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtApprovedAmount)
                            .addComponent(txtGrantRequested)
                            .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveAid)
                                .addGap(66, 66, 66)
                                .addComponent(btnApprove)
                                .addGap(76, 76, 76)
                                .addComponent(btnBack))
                            .addComponent(lblTitle))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitle)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudent)
                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMajor)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetUni)
                    .addComponent(txtTargetUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGrantRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrantRequested))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblGPA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApprovedAmount)
                        .addGap(18, 18, 18)
                        .addComponent(lblComments))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtApprovedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSaveAid)
                    .addComponent(btnApprove))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        StudyAbroadApplication app = request.getStudentApplication();
    if (app == null) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Error: Cannot find student application.");
        return;
    }
    
    if (!"Offer Accepted".equals(app.getStatus())) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "❌ Cannot approve aid yet!\n\n" +
            "Student must accept the offer first.\n" +
            "Current application status: " + app.getStatus() + "\n\n" +
            "Please wait for student to accept the offer.");
        return;
    }
    if (!app.isAidSaved()) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Error: Aid amount not saved yet.\n" +
            "Please save the aid amount first.");
        return;
    }
    
    app.setAidApproved(true);
    request.setStatus("Approved");
    
    double aidAmount = app.getGrantAmount();
    
    String currentResult = app.getResult() != null ? app.getResult() : "";
    app.setResult(currentResult + " | Financial Aid APPROVED: $" + aidAmount);
    
    String comments = txtComments.getText().trim();
    if (!comments.isEmpty()) {
        request.setResult("Financial aid approved: $" + aidAmount + " - " + comments);
    } else {
        request.setResult("Financial aid approved: $" + aidAmount);
    }
    
    javax.swing.JOptionPane.showMessageDialog(null, 
        "✅ Financial Aid Approved!\n\n" +
        "Student: " + app.getSender().getEmployee().getName() + "\n" +
        "Approved Amount: $" + aidAmount + "\n" +
        "Status: Approved\n\n" +
        "Student can now proceed with enrollment.");
    
    goBack();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        goBack();
        }                                       

        private void goBack() {
            userProcessContainer.remove(this);
            java.awt.Component[] componentArray = userProcessContainer.getComponents();
            java.awt.Component component = componentArray[componentArray.length - 1];
            FinancialAuditorWorkAreaJPanel dwjp = (FinancialAuditorWorkAreaJPanel) component;
            dwjp.populateTable(); // Refresh the table
            java.awt.CardLayout layout = (java.awt.CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAidActionPerformed
       String amtText = txtApprovedAmount.getText().trim();
    
    if (amtText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter an aid amount.");
        return;
    }
    
    double aidAmount = 0;
    try {
        aidAmount = Double.parseDouble(amtText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid amount format.");
        return;
    }
    
    if (aidAmount <= 0) {
        JOptionPane.showMessageDialog(null, "Amount must be greater than 0.");
        return;
    }
    
    StudyAbroadApplication app = request.getStudentApplication();
    if (app != null) {
        app.setAidSaved(true);
        app.setGrantAmount(aidAmount);
        
        String currentResult = app.getResult() != null ? app.getResult() : "";
        
        String comments = txtComments.getText().trim();
        if (!comments.isEmpty()) {
            app.setResult(currentResult + " | Aid: $" + aidAmount + " - " + comments);
        } else {
            app.setResult(currentResult + " | Aid: $" + aidAmount + " (Pending Acceptance)");
        }
    }
    
    request.setStatus("Aid Saved (Pending Student Acceptance)");
    request.setApprovedAmount(aidAmount);
    
    JOptionPane.showMessageDialog(null, 
        "Aid Amount Saved: $" + aidAmount + "\n" +
        "Student must accept offer before final approval.");
    
    goBack();
    }//GEN-LAST:event_btnSaveAidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveAid;
    private javax.swing.JLabel lblApprovedAmount;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblGrantRequested;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblTargetUni;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtApprovedAmount;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtGrantRequested;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtStudent;
    private javax.swing.JTextField txtTargetUni;
    // End of variables declaration//GEN-END:variables
}
